---
version: "3"

dotenv: [".env"]

includes:

  rclone:
    taskfile: .taskfiles/rclone.tasks.yml
    optional: true
    internal: true

  terraform:
    taskfile: .taskfiles/terraform.tasks.yml
    vars:
      TERRAFORM_ARGS: -var="repo_dir={{.ROOT_DIR}}"
    optional: true
    internal: true

tasks:
  default:
    cmds:
      - task -l
    silent: true

  setup:
    desc: "Set up repository for use"
    cmds:
      - task: rclone:install

  plan:
    desc: "Plan infrastructure"
    cmds:
      - task: terraform:init
      - task: terraform:fmt
      - task: terraform:validate
      - task: terraform:plan

  deploy:
    desc: "Deploy infrastructure"
    cmds:
      - task: terraform:init
      - task: terraform:fmt
      - task: terraform:validate
      - task: terraform:plan
      - task: terraform:apply

  destroy:
    desc: "Destroy infrastructure"
    cmds:
      - task: terraform:init
      - task: terraform:fmt
      - task: terraform:validate
      - task: terraform:plan
      - task: terraform:destroy

  update:
    desc: "Update repo"
    cmds:
      - rm -rf .taskfiles
      - git clone git@github.com:frozenfoxx/taskfiles.git .taskfiles
      - git pull --rebase
