---
version: "3"

dotenv: [".env"]

vars:
  ANSIBLE_ARGS: ""
  ANSIBLE_CONFIG: "{{.USER_WORKING_DIR}}/ansible/ansible.cfg"
  INVENTORY_PATH: '{{default "inventory" .INVENTORY_PATH}}'
  RCLONE_ARGS: ""
  TERRAFORM_ARGS: ""

includes:
  ansible:
    taskfile: .taskfiles/ansible.tasks.yml
    dir: "{{.USER_WORKING_DIR}}/ansible"
    internal: true

  git:
    taskfile:  .taskfiles/git.tasks.yml
    internal: true

  rclone:
    taskfile: .taskfiles/rclone.tasks.yml
    internal: true

  terraform:
    taskfile: .taskfiles/terraform.tasks.yml
    vars:
      TERRAFORM_ARGS: -var="repo_dir={{.USER_WORKING_DIR}}"
    internal: true

tasks:
  default:
    cmds:
      - task -l
    silent: true

  setup:
    desc: "Set up repository for use"
    cmds:
      - task: rclone:install
      - task: terraform:init
      - rm -rf ./ansible
      - git clone https://github.com/frozenfoxx/ansible-bricksandblocks.git ansible
      - task: git:reset:dir
        vars:
          CLI_ARGS: "./inventory"
        directory: "{{.USER_WORKING_DIR}}/ansible"
      - task: rclone:copy
        vars:
          RCLONE_SOURCE: "inventory:{{.INVENTORY_PATH}}/"
          RCLONE_DEST: "./inventory/"
        directory: "{{.USER_WORKING_DIR}}/ansible"
      - task: ansible:galaxy

  plan:
    desc: "Plan infrastructure"
    cmds:
      - task: terraform:init
      - task: terraform:fmt
      - task: terraform:validate
      - task: terraform:plan

  deploy:
    desc: "Deploy infrastructure"
    cmds:
      - task: terraform:init
      - task: terraform:fmt
      - task: terraform:validate
      - task: terraform:plan
      - task: terraform:apply

  destroy:
    desc: "Destroy infrastructure"
    cmds:
      - task: terraform:init
      - task: terraform:fmt
      - task: terraform:validate
      - task: terraform:plan
      - task: terraform:destroy
