---
version: "3"

vars:
  ANSIBLE_ARGS: ""
  RCLONE_ARGS: ""
  TERRAFORM_ARGS: ""

includes:
  ansible: .taskfiles/ansible.tasks.yml
  dir: ./ansible
  internal: true

  git: .taskfiles/git.tasks.yml
  internal: true

  rclone: .taskfiles/rclone.tasks.yml
  internal: true

  terraform: .taskfiles/terraform.tasks.yml
  internal: true

tasks:
  init:
    desc: "Initialize"
    cmds:
      - task: terraform:init

  deploy:
    desc: "Deploy infrastructure"
    cmds:
      - task: terraform:fmt
      - task: terraform:validate
      - task: terraform:plan
      - task: terraform:apply

  destroy:
    desc: "Destroy infrastructure"
    cmds:
      - task: terraform:fmt
      - task: terraform:validate
      - task: terraform:plan
      - task: terraform:destroy
